---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-cluster-machine-approver
  name: machine-approver-sa
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-approver
  namespace: openshift-config-managed
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - csr-controller-ca
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-approver
  namespace: openshift-config-managed
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-machine-approver
  name: machine-approver-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:controller:machine-approver
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:machine-approver
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:controller:machine-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-machine-approver
  name: machine-approver-sa
